FROM ubuntu:20.04

# Install common utilities from distribution package repository
RUN apt-get update && apt-get install -y \
    wget


# Install third-party EDA tools
RUN mkdir /prog

# oss-cad-suite
RUN cd /prog \
    && wget https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2024-03-20/oss-cad-suite-linux-x64-20240320.tgz \
    && tar -xvzf oss-cad-suite-linux-x64-20240320.tgz \
    && rm -f oss-cad-suite-linux-x64-20240320.tgz

# doesn't get sourced when running in distrobox
RUN echo "source /prog/oss-cad-suite/environment" >> /root/.bashrc