FROM ubuntu:24.04

# Install common utilities from distribution package repository
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    curl wget git git-lfs vim htop pkg-config build-essential zip \
    openssl libssl-dev


# Install third-party EDA tools
RUN mkdir /prog

# oss-cad-suite
RUN cd /prog \
    && wget -q https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2024-03-20/oss-cad-suite-linux-x64-20240320.tgz \
    && tar --no-same-owner -xvzf oss-cad-suite-linux-x64-20240320.tgz \
    && rm -f oss-cad-suite-linux-x64-20240320.tgz

# doesn't get sourced when running in distrobox
RUN echo "source /prog/oss-cad-suite/environment" >> /root/.bashrc

# Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
    | sh -s -- --default-toolchain stable -y

ENV PATH=/root/.cargo/bin:$PATH

# surfer
# install binary release
RUN wget -q https://gitlab.com/api/v4/projects/42073614/packages/generic/surfer/0.1.0/surfer_linux_0.1.0.zip \
    && unzip surfer_linux_0.1.0.zip \
    && rm -f surfer_linux_0.1.0.zip \
    && mv surfer /bin

# compile from source (not ideal due to large rust build directory)
# RUN cargo install --git https://gitlab.com/surfer-project/surfer surfer
